// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed.ts",
  },
  datasource: {
    url: 
      process.env["DATABASE_URL"] || 
      process.env["NARDLENS_DATABASE_URL"] || 
      process.env["NARDLENS_PRISMA_DATABASE_URL"] || 
      process.env["NARDLENS_POSTGRES_URL"] || 
      process.env["POSTGRES_PRISMA_URL"] || 
      process.env["POSTGRES_URL"] || 
      process.env["STRUCTORA_DATABASE_URL"],
  },
});
